### ISSUE TITLE
Question: Is home folder access required?

### ISSUE THREAD

**Issue by Gert-dev** [flathub/com.parsecgaming.parsec#12]
Hello

I'm not too familiar with Flatpaks yet, but do I understand correctly that the line `"--persist=."` in the configuration is essentially the same as `--filesystem=home` in that it bind mounts the user's actual `$HOME/.` (which becomes `$HOME`) into the container of Parsec as-is?

If so, is this absolutely required for the application to function, i.e. would it be possible to limit it to specific subfolders instead, or, barring that, would the application still function, albeit without having things such as the mentioned persistent login?

The unfortunate part of `persist` is that it cannot be revoked by something like Flatseal or `flatpak override`, and giving complete access to home [is essentially game over if the application is/becomes malicious](https://github.com/flatpak/flatpak/issues/3637).

Thanks in advance!

**Comment by SISheogorath** [comment]
That's a misunderstanding.

`--persistent=.` is not the same as `--filesystem=home`. The former means "act as if there was a empty homefolder that you, can do in what you like and is persistent", while the latter means "expose my actual home folder to the application"

Practically this means: If the app write something in `~/example.txt`, this will be actually written in `~/.var/app/com.parsecgaming.parsec/example.txt` when you use `--persistent=.`

While `--filesystem=home` would mean writing `~/example.txt` in the flatpak would result in `~/example.txt` outside of your flatpak.

I'm very aware of the permission problems flatpak has and actively work on reducing home filesystem access. So no worries, it's all fine here :) Parsec is using a virtual home, since it writes the entire application directly into `~/` which I why it requires `--persistent=.` and was one of the main motiviations to flatpak it in first place, as I really dislike cluttered home directories.

But that's for asking 👍🏻

**Comment by Gert-dev** [comment]
Fantastic, and glad to hear that I understood incorrectly - I did some searching and reading of the documentation before asking this question, but this nuance still wasn't entirely clear to me after that.

Thanks for taking the time to respond, for containerizing this application, and actively paying attention to these security and privacy caveats :+1:.
