### ISSUE TITLE
Please update from 150-78 to 150-81

### ISSUE THREAD

**Issue by nukeCrayon** [flathub/com.parsecgaming.parsec#15]
I can't connect to some people because they have a version 150-81 but this flatpak version is 150-78. Please fix.

**Comment by SISheogorath** [comment]
Hi, I looked into the topic, but since the parsec internal version is managed by parsecd itself, we have no real say in this. All we do is providing upstream parsecd with no modifications. It's then parsecd which decided whether it needs to update or not. The changed files are stored in the home directory of the user running parsec (in case of this flatpak, there is just an emulated home directory with the actual location being in `~/.var/app/com.parsecgaming.parsec/`.)

If you have any idea on how we can improve this process, I would be thankful :)

**Comment by nukeCrayon** [comment]
Thank you for explaining to me the process. Maybe parsec from Linux to Windows is not just compatible now.
