### ISSUE TITLE
Error -800 when logging in

### ISSUE THREAD

**Issue by jgillich** [flathub/com.parsecgaming.parsec#2]
Logging in with valid credentials:

![Screenshot from 2020-11-19 18-57-34](https://user-images.githubusercontent.com/347965/99704999-71a60280-2a99-11eb-804c-7f2e13d389d6.png)

OS is Fedora Silverblue 33

When I go the route of converting the deb and running it in a toolbox container, it works just fine, so it must be related to flatpak.

Console output:

```
$ flatpak run com.parsecgaming.parsec
sh: xdg-mime: command not found
[D 2020-11-19 19:04:02] uncurl_listen=-50021
[D 2020-11-19 19:04:02] os_readbin=0
```

Any ideas? Thanks!

**Comment by SISheogorath** [comment]
I can reproduce it, but I'm not sure why it takes place. I'll further investigate it.

**Comment by mindbeat** [comment]
I solved it with adding permission to home folder.
  - "--filesystem=home"

**Comment by SISheogorath** [comment]
The reason for the whole problem is that the current flatpak forces the version that was downloaded. It seems like parsec decided to change the API and requires an updated client version.

Sadly the parsec team doesn't consider proper packaging a priority and therefore they just download the newest version on startup and try to load it following their appdata config. This introduces two problems:

1. It requires the flatpak to persist those downloads, which hopefully doesn't pile up.
2. It requires the flatpak to make the appdata.json mutable without removing it from the initial setup, because otherwise the parsec client won't start.

My PR above solves the problem to some degree. The way better way would be, when the parsec team would provide a proper package, but my requests and general questions in that direction ended up unheard, so I hope that's enough.

**Comment by jgillich** [comment]
After removing the appdata.json symlink it's working for me. :+1: 

It looks like it downloads the latest version for every single startup. Possibly because appdata.json is being replaced in the launch script? We might only want to copy it to $HOME if it doesn't exist?

**Comment by SISheogorath** [comment]
I tried that and ended up with some sort of race-condition situation where parsec refused to start, because the `appdata.json` was in place but the `.so` file referenced in it, disappeared. Maybe I can write some additional verification code that makes it more optional.

**Comment by mindbeat** [comment]
I made a new pull request that solved this issue.

**Comment by mindbeat** [comment]
- "[ ! -e $HOME/appdata.json ] && cp /app/extra/share/parsec/skel/appdata.json $HOME"
          - "[ ! -e $HOME/parsecd-*.so ] && cp /app/extra/share/parsec/skel/parsecd-*.so $HOME"

**Comment by Kabouik** [comment]
I still get that issue on Guix System, is it still working for others above? I also get some errors in the terminal:

```
$ flatpak run com.parsecgaming.parsec --filesystem=home                                                                                                                                                              14:40:21
[D 2023-03-02 14:40:24] log: Parsec release (150-86e)
[D 2023-03-02 14:40:24] MTY_DeleteFile: 'remove' failed with errno 39
[D 2023-03-02 14:40:24] MTY_SOLoad: libssl.so.3: cannot open shared object file: No such file or directory
[D 2023-03-02 14:40:24] MTY_SOLoad: 'dlopen' failed to find 'libssl.so.3'
[D 2023-03-02 14:40:24] MTY_TLSHandshake: 'SSL_do_handhsake' failed with error -1:1
[D 2023-03-02 14:40:24] MTY_SOLoad: libcrypto.so.3: cannot open shared object file: No such file or directory
[D 2023-03-02 14:40:24] MTY_SOLoad: 'dlopen' failed to find 'libcrypto.so.3'
[D 2023-03-02 14:40:30] MTY_TLSHandshake: 'SSL_do_handhsake' failed with error -1:1
```

`libssl` and `libcrypto` are installed, but maybe the non-standard file hierarchy in Guix is causing trouble.
